### ISSUE TITLE
Keyboard shortcut?

### ISSUE THREAD

**Issue by dilzeem** [ksqsf/logseq-open-in-emacs#1]
Hi,

Everything works ( I had to change the elisp code for mysetup which ins Windows Logseq, but Emacs in WSL2)

Right now though I would really appreciate if we could use a shortcut to open this in Emacs from Logseq.
It seems like it would be possible based of this:

https://discuss.logseq.com/t/trigger-plugin-by-keyboard-shortcut/2200/3

Something like this I believe
```
    // register keyboard
    if (logseq.settings.keyboard) {
        logseq.App.registerCommandPalette({
            key: 'toggle_focus_mode_shortcut',
            label: 'Toggle Focus Mode Keyboard Shortcut',
            keybinding: {
                binding: logseq.settings.keyboard
            }
        }, () => {
            model.toggleFocus();
        });
    }
```

Thanks for making the plugin :)

**Comment by ksqsf** [comment]
Good idea, thanks!

I've added a keyboard shortcut (configurable, mod+o by default) in the new version. Let me know if there's anything not working properly.

**Comment by dilzeem** [comment]
Great thanks! Just checked it out and worked out of the box :) Have a great new year!
