### ISSUE TITLE
Feqture request: support wsl emacs

### ISSUE THREAD

**Issue by FelixHuoEZ** [ksqsf/logseq-open-in-emacs#2]
wsl emacs use the path `/mnt/c/blabla/`, so it should be conversion between original path and wsl path.

**Comment by ksqsf** [comment]
Hi, thanks for this idea! I do not own Windows environments atm, so I'd like some feedback on this.

Currently,

- The plugin obtains file paths like `C:\graph\xxx`
- but emacsclient in WSL only recognizes `/mnt/c/graph/xxx`

Therefore, it's desirable the plugin can modify file paths so that they are recognizable by emacsclient in WSL, something like:  

1. replace `\` by `/`
2. if the path starts with `X:/`, replace it with `/mnt/x/`

Can you confirm my observations?

(also cc @dilzeem who in #1 says they made it work on WSL2. Could you please share how you did it?)

**Comment by dilzeem** [comment]
Hi, 

It was just a change in the e-lisp code that you put in your emacs config. 
As you mentioned @ksqsf in point number 2 just replacing the start of the path. 

Code that did it is below.

```
  (use-package org-protocol
    :ensure org
    :config
    (add-to-list 'org-protocol-protocol-alist
                 '("org-find-file" :protocol "find-file" :function org-protocol-find-file :kill-client nil))
    (defun org-protocol-find-file (fname)
      "Process org-protocol://find-file?path= style URL."
      (let ((f (plist-get (org-protocol-parse-parameters fname nil '(:path)) :path)))
        (find-file (replace-regexp-in-string "C:/" "/mnt/c/" f))
        (raise-frame)
        (select-frame-set-input-focus (selected-frame)))))
```

**Comment by ksqsf** [comment]
Thanks @dilzeem !

I want to avoid maintaining something I cannot easily test, so I think we can update the README instead of changing the Logseq-side code.

@saccohuo This is what I intend to put up in the README, could you please verify if it works for you? Thanks in advance.

```elisp
  (defun org-protocol-find-file-fix-wsl-path (path)
    "Change Windows-style paths to WSL-style paths if inside WSL."
    (if (not (string-match-p "-[Mm]icrosoft" operating-system-release))
        path
      (save-match-data
        (if (/= 0 (string-match "^\\([a-zA-Z]\\):\\(/.*\\)" path))
            path
          (let ((volume (match-string-no-properties 1 path))
                (abspath (match-string-no-properties 2 path)))
            (format "/mnt/%s%s" (downcase volume) abspath))))))

  (defun org-protocol-find-file (fname)
    "Process org-protocol://find-file?path= style URL."
    (let ((f (plist-get (org-protocol-parse-parameters fname nil '(:path)) :path)))
      (find-file (org-protocol-find-file-fix-wsl-path f))
      (raise-frame)
      (select-frame-set-input-focus (selected-frame))))
```

**Comment by FelixHuoEZ** [comment]
> Thanks @dilzeem !
> 
> I want to avoid maintaining something I cannot easily test, so I think we can update the README instead of changing the Logseq-side code.
> 
> @saccohuo This is what I intend to put up in the README, could you please verify if it works for you? Thanks in advance.
> 
> ```emacs-lisp
>   (defun org-protocol-find-file-fix-wsl-path (path)
>     "Change Windows-style paths to WSL-style paths if inside WSL."
>     (if (not (string-match-p "-[Mm]icrosoft" operating-system-release))
>         path
>       (save-match-data
>         (if (/= 0 (string-match "^\\([a-zA-Z]\\):\\(/.*\\)" path))
>             path
>           (let ((volume (match-string-no-properties 1 path))
>                 (abspath (match-string-no-properties 2 path)))
>             (format "/mnt/%s%s" (downcase volume) abspath))))))
> 
>   (defun org-protocol-find-file (fname)
>     "Process org-protocol://find-file?path= style URL."
>     (let ((f (plist-get (org-protocol-parse-parameters fname nil '(:path)) :path)))
>       (find-file (org-protocol-find-file-fix-wsl-path f))
>       (raise-frame)
>       (select-frame-set-input-focus (selected-frame))))
> ```

It works well, many thanks!!!
