### ISSUE TITLE
Keep getting notification of error

### ISSUE THREAD

**Issue by kings2u** [ksqsf/logseq-open-in-emacs#4]
I keep getting a notification from logseq of an error: `:plugin.logseq-open-in-emacs/open-in-emacs-page Cannot read properties of undefined (reading 'forEach')`.  Do you have any advice? 

Thank you for this plugin!

**Comment by ksqsf** [comment]
Hi, could you please tell your Logseq version and the plugin version?

I only tested v0.0.3 on Logseq v0.9.1, so compatibility with old versions might be lost.

**Comment by kings2u** [comment]
Yes I’m on logseq v0.9.1 and plugin v0.0.3.

**Comment by kings2u** [comment]
Hmm I uninstalled and reinstalled the plugin and didn’t get an error. I'll close this for now. Sorry for the false alarm!

**Comment by ksqsf** [comment]
No problem. Glad it works for you!
